version: '3.3'

services:
  db: #container do MySQL
    image:  mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend
    
     

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend
      

volumes:
  db_data: {}
networks:
  backend:
    driver: bridge
# HzN)$KU&9R(YtvlHxS    (senha do wordpress)
# docker composer up  ---subir aplicação docker  
# docker composer down  ---desce aplicação docker
# docker composer up -d   ---subir aplicação docker  (sem pegar o terminal)
#  docker-compose down -v (Isso irá remover os volumes associados aos containers da aplicação. Isso é importante se você quiser excluir dados persistentes.)

# docker-compose down --rmi all ( Isso irá remover as imagens associadas aos serviços definidos no docker-compose.yml. Este passo é opcional, pois em alguns casos você pode querer manter as imagens para reutilização em instalações futuras. )




